### ISSUE TITLE
Can you provide the long base case stl file please!

### ISSUE THREAD

**Issue by scarrrr316** [connornishijima/Lixie_II_OSHW#2]
can you provide the long base case （in the bellow photo） stl file, please 
![image](https://user-images.githubusercontent.com/43269183/69530700-71ba1200-0fad-11ea-94aa-f0e54434c7e7.png)

**Comment by DasWookie** [comment]
I believe Connor used the 3 files he released in the files. They then snap together to form the single unit. Most printers don't have a large enough print area to be able to print the whole thing in one go, which is why I believe he split them into 3 parts (left, right, and center where you use as many center pieces as needed

**Comment by DasWookie** [comment]
https://github.com/connornishijima/Lixie_II_OSHW/tree/master/3D%20PRINTING

**Comment by scarrrr316** [comment]
> https://github.com/connornishijima/Lixie_II_OSHW/tree/master/3D%20PRINTING

thankyou, but I think that the long base in the picture is more beautiful than the short base that provided. if Connor does not send the long base STL file,  I just draw it by myself

**Comment by scarrrr316** [comment]
ok.......I draw it myself
